name: copellia
description: A refined Jellyfin-focused music player for macOS and beyond.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  flutter_cache_manager: ^3.3.1
  http: ^1.2.1
  intl: ^0.19.0
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
