name: coppelia
description: A refined, cross-platform Jellyfin-focused music player
publish_to: "none"
version: 0.0.3-alpha

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cached_network_image: ^3.3.1
    cupertino_icons: ^1.0.6
    flutter_svg: ^2.0.10
    flutter_cache_manager: ^3.3.1
    connectivity_plus: ^6.0.5
    http: ^1.2.1
    intl: ^0.19.0
    audio_service: ^0.18.15
    just_audio: ^0.10.5
    just_audio_background: ^0.0.1-beta.17
    path_provider: ^2.1.2
    palette_generator: ^0.3.3+3
    provider: ^6.1.2
    shared_preferences: ^2.2.2
    window_manager: ^0.3.8

dev_dependencies:
    flutter_lints: ^3.0.0
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter
    mocktail: ^1.0.3
    sqflite_common_ffi: ^2.3.3
    path_provider_platform_interface: ^2.1.2

flutter:
    uses-material-design: true
    assets:
        - assets/logo.svg
        - assets/logo.png
